# Generated by Django 4.2.7 on 2023-11-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_rename_full_name_universitymodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitymodel',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Полное название'),
        ),
    ]
