# Generated by Django 4.2.7 on 2023-11-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_universitymodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitymodel',
            name='abbreviated',
            field=models.CharField(max_length=250, unique=True, verbose_name='Сокращенное название'),
        ),
        migrations.AlterField(
            model_name='universitymodel',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Полное название'),
        ),
    ]
